// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Album struct {
	Uri  string
	Name string
}

type Artist struct {
	Uri  string
	Name string
}

type FriendActivity struct {
	Timestamp int64
	UserUri   sql.NullString
	TrackUri  sql.NullString
}

type Track struct {
	Uri        string
	Name       string
	ImageUrl   sql.NullString
	AlbumUri   sql.NullString
	ArtistUri  sql.NullString
	ContextUri sql.NullString
}

type TrackContext struct {
	Uri        string
	Name       string
	TrackIndex int64
}

type User struct {
	Uri      string
	Name     string
	ImageUrl sql.NullString
}
