// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createAlbum = `-- name: CreateAlbum :one

INSERT INTO Albums (uri, name)
VALUES (?1, ?2) RETURNING uri, name
`

type CreateAlbumParams struct {
	Uri  string
	Name string
}

// ALBUMS --
func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, createAlbum, arg.Uri, arg.Name)
	var i Album
	err := row.Scan(&i.Uri, &i.Name)
	return i, err
}

const createArtist = `-- name: CreateArtist :one

INSERT INTO Artists (uri, name)
VALUES (?1, ?2) RETURNING uri, name
`

type CreateArtistParams struct {
	Uri  string
	Name string
}

// ARTIST --
func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, arg.Uri, arg.Name)
	var i Artist
	err := row.Scan(&i.Uri, &i.Name)
	return i, err
}

const createFriendActivity = `-- name: CreateFriendActivity :one

INSERT INTO FriendActivity (timestamp, user_uri, track_uri)
VALUES (?1, ?2, ?3) RETURNING timestamp, user_uri, track_uri
`

type CreateFriendActivityParams struct {
	Timestamp int64
	UserUri   sql.NullString
	TrackUri  sql.NullString
}

// FRIENDAcActivity --
func (q *Queries) CreateFriendActivity(ctx context.Context, arg CreateFriendActivityParams) (FriendActivity, error) {
	row := q.db.QueryRowContext(ctx, createFriendActivity, arg.Timestamp, arg.UserUri, arg.TrackUri)
	var i FriendActivity
	err := row.Scan(&i.Timestamp, &i.UserUri, &i.TrackUri)
	return i, err
}

const createTrack = `-- name: CreateTrack :one

INSERT INTO Tracks (uri, name, image_url, album_uri, artist_uri, context_uri)
VALUES (?1, ?2, ?3, ?4, ?5, ?6) RETURNING uri, name, image_url, album_uri, artist_uri, context_uri
`

type CreateTrackParams struct {
	Uri        string
	Name       string
	ImageUrl   sql.NullString
	AlbumUri   sql.NullString
	ArtistUri  sql.NullString
	ContextUri sql.NullString
}

// TRACKS --
func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, createTrack,
		arg.Uri,
		arg.Name,
		arg.ImageUrl,
		arg.AlbumUri,
		arg.ArtistUri,
		arg.ContextUri,
	)
	var i Track
	err := row.Scan(
		&i.Uri,
		&i.Name,
		&i.ImageUrl,
		&i.AlbumUri,
		&i.ArtistUri,
		&i.ContextUri,
	)
	return i, err
}

const createTrackContext = `-- name: CreateTrackContext :one

INSERT INTO TrackContexts (uri, name, track_index)
VALUES (?1, ?2, ?3) RETURNING uri, name, track_index
`

type CreateTrackContextParams struct {
	Uri        string
	Name       string
	TrackIndex int64
}

// TRACK CONTEXT --
func (q *Queries) CreateTrackContext(ctx context.Context, arg CreateTrackContextParams) (TrackContext, error) {
	row := q.db.QueryRowContext(ctx, createTrackContext, arg.Uri, arg.Name, arg.TrackIndex)
	var i TrackContext
	err := row.Scan(&i.Uri, &i.Name, &i.TrackIndex)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO Users (uri, name, image_url)
VALUES (?1, ?2, ?3) RETURNING uri, name, image_url
`

type CreateUserParams struct {
	Uri      string
	Name     string
	ImageUrl sql.NullString
}

// USERS --
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Uri, arg.Name, arg.ImageUrl)
	var i User
	err := row.Scan(&i.Uri, &i.Name, &i.ImageUrl)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :one
DELETE
FROM Albums
WHERE uri = ?1 RETURNING uri, name
`

func (q *Queries) DeleteAlbum(ctx context.Context, uri string) (Album, error) {
	row := q.db.QueryRowContext(ctx, deleteAlbum, uri)
	var i Album
	err := row.Scan(&i.Uri, &i.Name)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :one
DELETE
FROM Artists
WHERE uri = ?1 RETURNING uri, name
`

func (q *Queries) DeleteArtist(ctx context.Context, uri string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, deleteArtist, uri)
	var i Artist
	err := row.Scan(&i.Uri, &i.Name)
	return i, err
}

const deleteFriendActivity = `-- name: DeleteFriendActivity :one
DELETE
FROM FriendActivity
WHERE user_uri = ?1
  AND track_uri = ?2 RETURNING timestamp, user_uri, track_uri
`

type DeleteFriendActivityParams struct {
	UserUri  sql.NullString
	TrackUri sql.NullString
}

func (q *Queries) DeleteFriendActivity(ctx context.Context, arg DeleteFriendActivityParams) (FriendActivity, error) {
	row := q.db.QueryRowContext(ctx, deleteFriendActivity, arg.UserUri, arg.TrackUri)
	var i FriendActivity
	err := row.Scan(&i.Timestamp, &i.UserUri, &i.TrackUri)
	return i, err
}

const deleteTrack = `-- name: DeleteTrack :one
DELETE
FROM Tracks
WHERE uri = ?1 RETURNING uri, name, image_url, album_uri, artist_uri, context_uri
`

func (q *Queries) DeleteTrack(ctx context.Context, uri string) (Track, error) {
	row := q.db.QueryRowContext(ctx, deleteTrack, uri)
	var i Track
	err := row.Scan(
		&i.Uri,
		&i.Name,
		&i.ImageUrl,
		&i.AlbumUri,
		&i.ArtistUri,
		&i.ContextUri,
	)
	return i, err
}

const deleteTrackContext = `-- name: DeleteTrackContext :one
DELETE
FROM TrackContexts
WHERE uri = ?1 RETURNING uri, name, track_index
`

func (q *Queries) DeleteTrackContext(ctx context.Context, uri string) (TrackContext, error) {
	row := q.db.QueryRowContext(ctx, deleteTrackContext, uri)
	var i TrackContext
	err := row.Scan(&i.Uri, &i.Name, &i.TrackIndex)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE
FROM Users
WHERE uri = ?1 RETURNING uri, name, image_url
`

func (q *Queries) DeleteUser(ctx context.Context, uri string) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, uri)
	var i User
	err := row.Scan(&i.Uri, &i.Name, &i.ImageUrl)
	return i, err
}

const getAlbumByUri = `-- name: GetAlbumByUri :one
SELECT uri, name
FROM Albums
WHERE uri = ?1
`

func (q *Queries) GetAlbumByUri(ctx context.Context, uri string) (Album, error) {
	row := q.db.QueryRowContext(ctx, getAlbumByUri, uri)
	var i Album
	err := row.Scan(&i.Uri, &i.Name)
	return i, err
}

const getArtistByUri = `-- name: GetArtistByUri :one
SELECT uri, name
FROM Artists
WHERE uri = ?1
`

func (q *Queries) GetArtistByUri(ctx context.Context, uri string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByUri, uri)
	var i Artist
	err := row.Scan(&i.Uri, &i.Name)
	return i, err
}

const getLastFriendActivityByUserUri = `-- name: GetLastFriendActivityByUserUri :one
SELECT timestamp, user_uri, track_uri
FROM FriendActivity
WHERE user_uri = ?1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLastFriendActivityByUserUri(ctx context.Context, userUri sql.NullString) (FriendActivity, error) {
	row := q.db.QueryRowContext(ctx, getLastFriendActivityByUserUri, userUri)
	var i FriendActivity
	err := row.Scan(&i.Timestamp, &i.UserUri, &i.TrackUri)
	return i, err
}

const getTrackByUri = `-- name: GetTrackByUri :one
SELECT uri, name, image_url, album_uri, artist_uri, context_uri
FROM Tracks
WHERE uri = ?1
`

func (q *Queries) GetTrackByUri(ctx context.Context, uri string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackByUri, uri)
	var i Track
	err := row.Scan(
		&i.Uri,
		&i.Name,
		&i.ImageUrl,
		&i.AlbumUri,
		&i.ArtistUri,
		&i.ContextUri,
	)
	return i, err
}

const getTrackContextByUri = `-- name: GetTrackContextByUri :one
SELECT uri, name, track_index
FROM TrackContexts
WHERE uri = ?1
`

func (q *Queries) GetTrackContextByUri(ctx context.Context, uri string) (TrackContext, error) {
	row := q.db.QueryRowContext(ctx, getTrackContextByUri, uri)
	var i TrackContext
	err := row.Scan(&i.Uri, &i.Name, &i.TrackIndex)
	return i, err
}

const getUserByUri = `-- name: GetUserByUri :one
SELECT uri, name, image_url
FROM Users
WHERE uri = ?1
`

func (q *Queries) GetUserByUri(ctx context.Context, uri string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUri, uri)
	var i User
	err := row.Scan(&i.Uri, &i.Name, &i.ImageUrl)
	return i, err
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE Albums
SET name = ?2
WHERE uri = ?1 RETURNING uri, name
`

type UpdateAlbumParams struct {
	Uri  string
	Name string
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, updateAlbum, arg.Uri, arg.Name)
	var i Album
	err := row.Scan(&i.Uri, &i.Name)
	return i, err
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE Artists
SET name = ?2
WHERE uri = ?1 RETURNING uri, name
`

type UpdateArtistParams struct {
	Uri  string
	Name string
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, updateArtist, arg.Uri, arg.Name)
	var i Artist
	err := row.Scan(&i.Uri, &i.Name)
	return i, err
}

const updateFriendActivityTimestamp = `-- name: UpdateFriendActivityTimestamp :one
UPDATE FriendActivity
SET timestamp = ?2
WHERE user_uri = ?1
  AND track_uri = ?3 RETURNING timestamp, user_uri, track_uri
`

type UpdateFriendActivityTimestampParams struct {
	UserUri   sql.NullString
	Timestamp int64
	TrackUri  sql.NullString
}

func (q *Queries) UpdateFriendActivityTimestamp(ctx context.Context, arg UpdateFriendActivityTimestampParams) (FriendActivity, error) {
	row := q.db.QueryRowContext(ctx, updateFriendActivityTimestamp, arg.UserUri, arg.Timestamp, arg.TrackUri)
	var i FriendActivity
	err := row.Scan(&i.Timestamp, &i.UserUri, &i.TrackUri)
	return i, err
}

const updateTrack = `-- name: UpdateTrack :one
UPDATE Tracks
SET name        = ?2,
    image_url   = ?3,
    album_uri   = ?4,
    artist_uri  = ?5,
    context_uri = ?6
WHERE uri = ?1 RETURNING uri, name, image_url, album_uri, artist_uri, context_uri
`

type UpdateTrackParams struct {
	Uri        string
	Name       string
	ImageUrl   sql.NullString
	AlbumUri   sql.NullString
	ArtistUri  sql.NullString
	ContextUri sql.NullString
}

func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, updateTrack,
		arg.Uri,
		arg.Name,
		arg.ImageUrl,
		arg.AlbumUri,
		arg.ArtistUri,
		arg.ContextUri,
	)
	var i Track
	err := row.Scan(
		&i.Uri,
		&i.Name,
		&i.ImageUrl,
		&i.AlbumUri,
		&i.ArtistUri,
		&i.ContextUri,
	)
	return i, err
}

const updateTrackContext = `-- name: UpdateTrackContext :one
UPDATE TrackContexts
SET name        = ?2,
    track_index = ?3
WHERE uri = ?1 RETURNING uri, name, track_index
`

type UpdateTrackContextParams struct {
	Uri        string
	Name       string
	TrackIndex int64
}

func (q *Queries) UpdateTrackContext(ctx context.Context, arg UpdateTrackContextParams) (TrackContext, error) {
	row := q.db.QueryRowContext(ctx, updateTrackContext, arg.Uri, arg.Name, arg.TrackIndex)
	var i TrackContext
	err := row.Scan(&i.Uri, &i.Name, &i.TrackIndex)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE Users
SET name      = ?2,
    image_url = ?3
WHERE uri = ?1 RETURNING uri, name, image_url
`

type UpdateUserParams struct {
	Uri      string
	Name     string
	ImageUrl sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Uri, arg.Name, arg.ImageUrl)
	var i User
	err := row.Scan(&i.Uri, &i.Name, &i.ImageUrl)
	return i, err
}
